# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lady/Programming/C++/Projects/Simulation

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lady/Programming/C++/Projects/Simulation

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lady/Programming/C++/Projects/Simulation/CMakeFiles /home/lady/Programming/C++/Projects/Simulation//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lady/Programming/C++/Projects/Simulation/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named simulation

# Build rule for target.
simulation: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 simulation
.PHONY : simulation

# fast build rule for target.
simulation/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulation.dir/build.make CMakeFiles/simulation.dir/build
.PHONY : simulation/fast

src/PointMass.o: src/PointMass.cpp.o
.PHONY : src/PointMass.o

# target to build an object file
src/PointMass.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulation.dir/build.make CMakeFiles/simulation.dir/src/PointMass.cpp.o
.PHONY : src/PointMass.cpp.o

src/PointMass.i: src/PointMass.cpp.i
.PHONY : src/PointMass.i

# target to preprocess a source file
src/PointMass.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulation.dir/build.make CMakeFiles/simulation.dir/src/PointMass.cpp.i
.PHONY : src/PointMass.cpp.i

src/PointMass.s: src/PointMass.cpp.s
.PHONY : src/PointMass.s

# target to generate assembly for a file
src/PointMass.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulation.dir/build.make CMakeFiles/simulation.dir/src/PointMass.cpp.s
.PHONY : src/PointMass.cpp.s

src/SimObject.o: src/SimObject.cpp.o
.PHONY : src/SimObject.o

# target to build an object file
src/SimObject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulation.dir/build.make CMakeFiles/simulation.dir/src/SimObject.cpp.o
.PHONY : src/SimObject.cpp.o

src/SimObject.i: src/SimObject.cpp.i
.PHONY : src/SimObject.i

# target to preprocess a source file
src/SimObject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulation.dir/build.make CMakeFiles/simulation.dir/src/SimObject.cpp.i
.PHONY : src/SimObject.cpp.i

src/SimObject.s: src/SimObject.cpp.s
.PHONY : src/SimObject.s

# target to generate assembly for a file
src/SimObject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulation.dir/build.make CMakeFiles/simulation.dir/src/SimObject.cpp.s
.PHONY : src/SimObject.cpp.s

src/Simulation.o: src/Simulation.cpp.o
.PHONY : src/Simulation.o

# target to build an object file
src/Simulation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulation.dir/build.make CMakeFiles/simulation.dir/src/Simulation.cpp.o
.PHONY : src/Simulation.cpp.o

src/Simulation.i: src/Simulation.cpp.i
.PHONY : src/Simulation.i

# target to preprocess a source file
src/Simulation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulation.dir/build.make CMakeFiles/simulation.dir/src/Simulation.cpp.i
.PHONY : src/Simulation.cpp.i

src/Simulation.s: src/Simulation.cpp.s
.PHONY : src/Simulation.s

# target to generate assembly for a file
src/Simulation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulation.dir/build.make CMakeFiles/simulation.dir/src/Simulation.cpp.s
.PHONY : src/Simulation.cpp.s

src/Vec3D.o: src/Vec3D.cpp.o
.PHONY : src/Vec3D.o

# target to build an object file
src/Vec3D.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulation.dir/build.make CMakeFiles/simulation.dir/src/Vec3D.cpp.o
.PHONY : src/Vec3D.cpp.o

src/Vec3D.i: src/Vec3D.cpp.i
.PHONY : src/Vec3D.i

# target to preprocess a source file
src/Vec3D.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulation.dir/build.make CMakeFiles/simulation.dir/src/Vec3D.cpp.i
.PHONY : src/Vec3D.cpp.i

src/Vec3D.s: src/Vec3D.cpp.s
.PHONY : src/Vec3D.s

# target to generate assembly for a file
src/Vec3D.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulation.dir/build.make CMakeFiles/simulation.dir/src/Vec3D.cpp.s
.PHONY : src/Vec3D.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulation.dir/build.make CMakeFiles/simulation.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulation.dir/build.make CMakeFiles/simulation.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulation.dir/build.make CMakeFiles/simulation.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... simulation"
	@echo "... src/PointMass.o"
	@echo "... src/PointMass.i"
	@echo "... src/PointMass.s"
	@echo "... src/SimObject.o"
	@echo "... src/SimObject.i"
	@echo "... src/SimObject.s"
	@echo "... src/Simulation.o"
	@echo "... src/Simulation.i"
	@echo "... src/Simulation.s"
	@echo "... src/Vec3D.o"
	@echo "... src/Vec3D.i"
	@echo "... src/Vec3D.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

